server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/


# Logging
logging.level.com.leetcode=INFO
logging.level.org.springframework.cloud.gateway=INFO


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never



# Kubernetes-specific (e.g., service discovery)
# spring.cloud.kubernetes.discovery.enabled=true